CREATE USER Social IDENTIFIED BY socpass DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";


GRANT CREATE TRIGGER TO Social ;
GRANT CREATE SEQUENCE TO Social ;
GRANT CREATE TABLE TO Social ;
GRANT CREATE PROCEDURE TO Social ;
GRANT CREATE SYNONYM TO Social ;
GRANT CREATE VIEW TO Social ;
GRANT CREATE TYPE TO Social ;
GRANT CREATE SESSION TO Social ;


ALTER USER Social QUOTA 1024M ON USERS;